<a href="https://colab.research.google.com/github/JayanthJakkula/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# array operations
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",a+b)# ele vise add
print("sub:",a-b)
print("mul:",a*b)
print(a*2)


addition: [5 7 9]
sub: [-3 -3 -3]
mul: [ 4 10 18]
[2 4 6]


In [ ]:
a=np.array([[1,2,3],[6,7,8],[3,4,5]])
b=np.array([[4,5,6],[5,6,8],[5,6,4]])
print("Dot product:",np.dot(a,b))

Dot product: [[ 29  35  34]
 [ 99 120 124]
 [ 57  69  70]]


In [ ]:
#broadcasting
a=np.array([1,2,3])
b=4
print(a+b)

[5 6 7]


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print("Apples shipped on wednesday:",shipments[0,2])
print("orange shipped on sunday:",shipments[1,6])
print("Mon-fri:",shipments[0:5,0:5])
print("sat and sun:",shipments[:,5:7])
print("Apples shipped from wed to sat:",shipments[0,2:6])
shipments[0,5]=100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
Apples shipped on wednesday: 55
orange shipped on sunday: 75
Mon-fri: [[50 60 55 70 65]
 [40 45 50 60 55]]
sat and sun: [[80 90]
 [70 75]]
Apples shipped from wed to sat: [55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(arr.ndim)
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)
print(arr.ndim)

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
(2, 2, 3)
3


In [ ]:
# zero array
import numpy as np
z=np.zeros((2,3))
print(z)
# ones array
z=np.ones((2,3))
print(z)
# random values
a=np.random.random((2,2))
print(a)
#identity matrix
a=np.eye(3)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.42695569 0.89989207]
 [0.82707495 0.9774121 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Array Attributes
a=np.array([[1,2,3],[4,5,6]])
print("Shape:",a.shape)
print("Data type:",a.dtype)
print("size:",a.size)
print("no.of dimensions:",a.ndim)


Shape: (2, 3)
Data type: int64
size: 6
no.of dimensions: 2


In [ ]:
# temparature data
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Shape:",temp_data.shape)
print("Data type:",temp_data.dtype)
print("size:",temp_data.size)
print("no.of dimensions:",temp_data.ndim)
updated_temp_data=np.append(temp_data,[[21,22,23]],axis=0)
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
green_house_identity=np.eye(3)
print(sensor_error_flags)
print(green_house_identity)

[[22 25 20]
 [24 26 23]]
Shape: (2, 3)
Data type: int64
size: 6
no.of dimensions: 2
[[22 25 20]
 [24 26 23]
 [21 22 23]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# universal functions
a=np.array([1,2,3])
print("Exponention:",np.exp(a))
print("Sqrt:",np.sqrt(a))
print("--logorithm--")
print("log:",np.log(a))


print("----trigonometic---")
print("sin:",np.sin(a))
print("cos:",np.cos(a))
print("tan:",np.tan(a))
print("arcsin:",np.arcsin(a))

print("-----aggregation:-----")
print("sum:",np.sum(a))
print("min:",np.min(a))
print("max:",np.max(a))
print("mean:",np.mean(a))
print("median:",np.median(a))
print("standard deviation:",np.std(a))
print("variance:",np.var(a))


print("unique elements:",np.unique(a))
print("sort:",np.sort(a))
print("sort in descending order:",np.sort(a)[::-1])
print("ceil:",np.ceil(a))
print("floor:",np.floor(a))
print("round:",np.round(a))
print("multiply:",np.multiply(a,2))
print("divide:",np.divide(a,2))
print("subtract:",np.subtract(a,2))
print("add:",np.add(a,2))



Exponention: [ 2.71828183  7.3890561  20.08553692]
Sqrt: [1.         1.41421356 1.73205081]
--logorithm--
log: [0.         0.69314718 1.09861229]
----trigonometic---
sin: [0.84147098 0.90929743 0.14112001]
cos: [ 0.54030231 -0.41614684 -0.9899925 ]
tan: [ 1.55740772 -2.18503986 -0.14254654]
arcsin: [1.57079633        nan        nan]
-----aggregation:-----
sum: 6
min: 1
max: 3
mean: 2.0
median: 2.0
standard deviation: 0.816496580927726
variance: 0.6666666666666666
unique elements: [1 2 3]
sort: [1 2 3]
sort in descending order: [3 2 1]
ceil: [1. 2. 3.]
floor: [1. 2. 3.]
round: [1 2 3]
multiply: [2 4 6]
divide: [0.5 1.  1.5]
subtract: [-1  0  1]
add: [3 4 5]


/tmp/ipython-input-2025365412.py:13: RuntimeWarning: invalid value encountered in arcsin
  print("arcsin:",np.arcsin(a))


In [ ]:
# task 3
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,9,7]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print(production_all)
print("dimension:",production_all.ndim)
print("shape:",production_all.shape)
print("dATATyPE:",production_all.dtype)
print("size:",production_all.size)

print("-----Aggregation---")

total_per_farm=production_all.sum(axis=(1,2))
print("total_per_farm:",total_per_farm)
print("mean_per_farm:",production_all.mean(axis=(1,2)))
print("max_per_farm:",production_all.max(axis=(1,2)))
print("min_per_farm:",production_all.min(axis=(1,2)))
print("standard_deviation_per_farm:",production_all.std(axis=(1,2)))
print("variance_per_farm:",production_all.var(axis=(1,2)))


hours_weigths=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hours_weigths)
print("weighted_per_panel:",weighted_per_panel)


print("add 0.5 to farmB:",production_all[1]+0.5)

form_means=np.mean(production_all,axis=(1,2))

form_std=np.std(production_all,axis=(1,2))
normalized=(production_all-form_means)/form_std
print("Normalized :",normalized)
print("normalized shape:",normalized.shape)
print("normalized dimension:",normalized.ndim)
print("normalized data type:",normalized.dtype)
print("normalized size:",normalized.size)
print()

print("--aggregation---")
print("sum:",np.sum(normalized))
print("mean:",np.mean(normalized))
print("max:",np.max(normalized))
print("min:",np.min(normalized))
print("standard deviation:",np.std(normalized))
print("variance:",np.var(normalized))

print()
print("--trigonometry--")
print("sin:",np.sin(normalized))
print("cos:",np.cos(normalized))
print("tan:",np.tan(normalized))


print()

print("floor:",np.floor(normalized))
print("ceil:",np.ceil(normalized))
print("round:",np.round(normalized))


print("--logical operartions---")
h=production_all>20
e=np.array([[1,0,1],[]])










[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  9  7]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
dimension: 3
shape: (3, 4, 3)
dATATyPE: int64
size: 36
-----Aggregation---
total_per_farm: [126 234 174]
mean_per_farm: [10.5 19.5 14.5]
max_per_farm: [14 23 18]
min_per_farm: [ 7 16 11]
standard_deviation_per_farm: [1.97905701 1.97905701 1.97905701]
variance_per_farm: [3.91666667 3.91666667 3.91666667]
weighted_per_panel: [[25.25 23.   29.5  18.25]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
add 0.5 to farmB: [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]
Normalized : [[[-0.25264558 -3.78968364 -1.76851903]
  [-0.75793673 -4.2949748  -2.27381019]
  [ 0.75793673 -3.28439249 -0.25264558]
  [-1.26322788 -5.3055571  -3.78968364]]

 [[ 4.80026595 -0.25264558  3.28439249]
  [ 3.78968364  0.25264558  2.27381019]
  [ 5.81084826  1.76851903  3.28439249]
  [ 3.28439249 -0.75793673  0.75793673]]

 [[

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# reshaping arrays
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b=a.reshape(3,2)
print("After reshaping")
print(b)
print(b.shape)


In [ ]:
# stacking
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([10,11,12,13,14,15,16,17,18])
print("horizental stacking:",np.hstack((a,b)))
print("vertical stacking :",np.vstack((a,b)))


In [ ]:
#spliting
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(a,3))

In [ ]:
# advanced indexing'

print("boolean indexing")
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[a>5])
print(a[a%2==0])


print()
print("fancy")
indices=[0,2]
print(a[indices])

In [ ]:
#view
print("using view")
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
print(view)
print()
#copy
print("using copy")
arr=np.array([1,2,3])
copy=arr.copy()
copy[0]=10
print(arr)
print(copy)

In [ ]:
# saving and loading
print("save to file")
a=np.array([1,2,3,4,5])
np.save("array",a)

print("load the file")
b=np.load("array.npy")
print(b)



In [ ]:
# task Array Creation
a=np.arange(10,51)

print(a)
print()

print("Random numbers b/w 0 and 1:")
b=np.random.rand(3,3)
print(b)

print("shape:",a.shape)
print("dimension:",a.ndim)
print("data type:",a.dtype)
print("size:",a.size)
print()

print("--basic operations")

print(" add  5 to 1d array:",a+5)
print()
print("mul 2 t0 2d array:",b*2)
print()


print("indexing")
print()
arr=np.arange(1,26)
arr=arr.reshape(5,5)
print(arr)
print(arr.ndim)
print("first row:",arr[0,:])

print("last row :",arr[4,:])
print("sub arry of 1st 3 row and 1st 2 columns:",arr[0:3,0:2])

print()
print("--Aggregation--")
print()
r=np.random.randint(10,101,size=10)
print(r)
print("sum:",np.sum(r))
print("mean:",np.mean(r))
print("max:",np.max(r))
print("min:",np.min(r))
print("standard deviation:",np.std(r))

print()
print("reshaping")
a=np.arange(1,13)
a=a.reshape(3,4)
print(a)
print()

print("broadcasting")
a=np.ones((3,3),dtype=int)

print(a)

b=np.array([1,2,3])
print(b)
print(a+b)
print()
print("filtering")
a=np.random.randint(1,51,size=5)
print(a)
print(a[a%5==0])


print("2d array multiplication")
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.dot(a,b))

print()
#advANCED indexing
a=np.arange(1,17).reshape(4,4)
print("diagonal ele of array 4*4:")
print(a[[0,1,2,3],[0,1,2,3]])





[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Random numbers b/w 0 and 1:
[[0.0878469  0.01371529 0.78942866]
 [0.82779646 0.5821054  0.80235693]
 [0.02162845 0.35367811 0.21957193]]
shape: (41,)
dimension: 1
data type: int64
size: 41

--basic operations
 add  5 to 1d array: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

mul 2 t0 2d array: [[0.17569381 0.02743057 1.57885732]
 [1.65559292 1.16421081 1.60471387]
 [0.0432569  0.70735622 0.43914386]]

indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2
first row: [1 2 3 4 5]
last row : [21 22 23 24 25]
sub arry of 1st 3 row and 1st 2 columns: [[ 1  2]
 [ 6  7]
 [11 12]]

--Aggregation--

[75 16 35 14 48 20 96 32 31 60]
sum: 427
mean: 42.7
max: 96
min: 14
standard deviation: 25.640007800310826

reshaping
[[ 1  2  3  4]
 [ 5  6  7  8